# Generated by Django 3.2.3 on 2021-10-30 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Customers First Name', max_length=48, null=True)),
                ('last_name', models.CharField(help_text='Customers Last Name', max_length=64, null=True)),
                ('email', models.CharField(help_text='Customers Email', max_length=128, null=True)),
                ('user', models.OneToOneField(help_text='The User assigned to this Customer', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
