# Generated by Django 3.2.3 on 2021-10-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='blank.png', help_text='Image for this Product', null=True, upload_to='product_images/')),
                ('name', models.CharField(help_text='Name of this Product', max_length=64, null=True)),
                ('range', models.CharField(help_text='Product Range this Product belongs to', max_length=64, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Product Price', max_digits=8)),
                ('description', models.TextField(help_text='Description for this Product', max_length=512, null=True)),
                ('duration', models.CharField(help_text='How long does this product last for?', max_length=16, null=True)),
                ('fragrance', models.CharField(help_text='What does this product smell like?', max_length=16, null=True)),
                ('type', models.CharField(help_text='What type of product is this?', max_length=16, null=True)),
                ('color', models.CharField(help_text='What is the color of this product?', max_length=16, null=True)),
                ('estimated_timeframe', models.CharField(help_text='How long will it take to be delivered?', max_length=16, null=True)),
            ],
        ),
    ]
