# Generated by Django 3.2.3 on 2021-10-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='blank.png', help_text='Customers Avatar Image', upload_to='user_avatars/'),
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, help_text='Rating given to this Product?', max_digits=4)),
                ('review', models.CharField(help_text='Rating for this Product', max_length=256, null=True)),
                ('product', models.ForeignKey(help_text='Product associated to Review', on_delete=django.db.models.deletion.CASCADE, to='amplifiedbeautyaus.product')),
                ('user', models.ForeignKey(help_text='User that gave the review', on_delete=django.db.models.deletion.CASCADE, to='amplifiedbeautyaus.customer')),
            ],
        ),
    ]
