# Generated by Django 3.2.3 on 2021-10-30 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0003_auto_20211030_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviews',
            name='product',
            field=models.ForeignKey(help_text='Product associated to Review', on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='amplifiedbeautyaus.product'),
        ),
    ]
