# Generated by Django 3.2.3 on 2021-11-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0005_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bookmarked_tips',
            field=models.ManyToManyField(to='amplifiedbeautyaus.Tips'),
        ),
    ]
