# Generated by Django 3.2.3 on 2021-11-22 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0006_customer_bookmarked_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Text for this Notification', max_length=256, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, help_text='The Time and Date this Notification was received')),
                ('user', models.ForeignKey(help_text='Customer that received this Notification', on_delete=django.db.models.deletion.CASCADE, to='amplifiedbeautyaus.customer')),
            ],
        ),
    ]
