# Generated by Django 3.2.3 on 2021-12-13 23:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0009_productrange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='amplifiedbeautyaus.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default='1')),
                ('sub_total', models.DecimalField(decimal_places=2, default='1', max_digits=10)),
                ('item_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('cart', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='cart_details', to='amplifiedbeautyaus.cart')),
                ('product', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='amplifiedbeautyaus.product')),
            ],
        ),
    ]
