# Generated by Django 3.2.3 on 2021-12-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0010_cart_cartdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrange',
            name='color',
            field=models.CharField(help_text='What color does this Range come in?', max_length=24, null=True),
        ),
    ]
