# Generated by Django 3.2.3 on 2021-12-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0011_productrange_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviews',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, help_text='Date this review was added', null=True),
        ),
    ]
