# Generated by Django 3.2.3 on 2021-12-14 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0012_productreviews_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='range',
            field=models.ForeignKey(help_text='Product Range for this Product', null=True, on_delete=django.db.models.deletion.CASCADE, to='amplifiedbeautyaus.productrange'),
        ),
    ]
