# Generated by Django 3.2.3 on 2021-12-14 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0013_alter_product_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='range',
        ),
    ]
