# Generated by Django 3.2.3 on 2021-12-14 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0014_remove_product_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_range',
            field=models.ForeignKey(default='1', help_text='Product Range for this Product', null=True, on_delete=django.db.models.deletion.CASCADE, to='amplifiedbeautyaus.productrange'),
        ),
        migrations.AddField(
            model_name='product',
            name='range',
            field=models.CharField(help_text='Product Range this Product belongs to', max_length=64, null=True),
        ),
    ]
