# Generated by Django 3.2.3 on 2022-03-02 01:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0015_auto_20211214_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_range',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='FF0000', help_text='What is the color of this product?', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
