# Generated by Django 3.2.3 on 2022-03-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0017_product_product_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='range',
        ),
        migrations.AlterField(
            model_name='productrange',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='amplifiedbeautyaus.Product'),
        ),
    ]
