# Generated by Django 3.2.3 on 2022-03-02 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0019_customeraddresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bookmarked_tips',
            field=models.ManyToManyField(blank=True, null=True, to='amplifiedbeautyaus.Tips'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wishlisted_products',
            field=models.ManyToManyField(blank=True, null=True, to='amplifiedbeautyaus.Product'),
        ),
        migrations.AlterField(
            model_name='customeraddresses',
            name='customer',
            field=models.ForeignKey(help_text='The Customer that created this delivery address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='amplifiedbeautyaus.customer'),
        ),
    ]
