# Generated by Django 3.2.3 on 2022-03-05 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0021_cart_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(blank=True, help_text='Delivery Address for this Order', null=True, on_delete=django.db.models.deletion.CASCADE, to='amplifiedbeautyaus.customeraddresses')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='amplifiedbeautyaus.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default='1')),
                ('sub_total', models.DecimalField(decimal_places=2, default='1', max_digits=10)),
                ('item_notes', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='amplifiedbeautyaus.order')),
                ('product', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='amplifiedbeautyaus.product')),
            ],
        ),
    ]
