# Generated by Django 3.2.3 on 2022-03-06 01:57

import amplifiedbeautyaus.models.password_reset_codes
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amplifiedbeautyaus', '0022_order_orderdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=amplifiedbeautyaus.models.password_reset_codes.generate_code, max_length=6)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('used', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
