# Generated by Django 3.2.3 on 2022-03-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0029_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_user_id',
            field=models.CharField(help_text='Users Stripe ID', max_length=128, null=True),
        ),
    ]
