# Generated by Django 3.2.3 on 2022-03-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0030_customer_stripe_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Image for this Product', null=True, upload_to='product_images/')),
                ('product', models.ForeignKey(help_text='Product for this Image', null=True, on_delete=django.db.models.deletion.CASCADE, to='amplifiedbeautyaus.product')),
            ],
        ),
    ]
