# Generated by Django 3.2.3 on 2022-03-23 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0031_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='product',
            field=models.ForeignKey(help_text='Product for this Image', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='amplifiedbeautyaus.product'),
        ),
    ]
