# Generated by Django 3.2.3 on 2022-03-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0032_alter_productimages_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(help_text='Image for this Product', null=True, upload_to='product_images/'),
        ),
    ]
