# Generated by Django 5.1.3 on 2024-11-14 03:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplifiedbeautyaus', '0035_customer_payment_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='bookmarked_tips',
            field=models.ManyToManyField(blank=True, to='amplifiedbeautyaus.tips'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wishlisted_products',
            field=models.ManyToManyField(blank=True, to='amplifiedbeautyaus.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='FF0000', help_text='What is the color of this product?', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='productrange',
            name='products',
            field=models.ManyToManyField(blank=True, to='amplifiedbeautyaus.product'),
        ),
    ]
